version: "3.8"

services:
  backend:
    container_name: moyza_backend

    build:
      context: ./backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    restart: always

    volumes:
      - ./storage:/app/storage

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - moyza_network

networks:
  moyza_network:
    driver: bridge