from sqlalchemy.orm import declarative_base
Base = declarative_base()

from app.models.company import Company
from app.models.user import User
from app.models.client import Client
from app.models.role import Role
from app.models.permission import Permission
from app.models.role_permission import RolePermission
from app.models.agent import Agent
from app.models.property import Property
from app.models.report import Report
from app.models.property_price_history import PropertyPriceHistory
from app.models.property_interaction import PropertyInteraction
from app.models.property_status_history import PropertyStatusHistory
from app.models.property_visit import PropertyVisit
from app.models.visit_audit_log import VisitAuditLog
from app.models.visit_otp_verification import VisitOTPVerification
from app.models.visit_whatsapp_log import VisitWhatsappLog
from app.models.report_job_log import ReportJobLog
from app.models.ai_analysis_log import AIAnalysisLog
from app.models.property_alert import PropertyAlert
from app.models.alert_follow_up import AlertFollowUp
from app.models.buyer import Buyer
from app.models.buyer_search_criteria import BuyerSearchCriteria
from app.models.user_activity_log import UserActivityLog
from app.models.property_change_log import PropertyChangeLog
from app.models.agent_performance_report import AgentPerformanceReport
from app.models.agent_performance_target import AgentPerformanceTarget
from app.models.notification import Notification
