"""property visits

Revision ID: 711ff9f390ef
Revises: 9621ab45ec8c
Create Date: 2026-06-02 22:43:21.784979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711ff9f390ef'
down_revision: Union[str, Sequence[str], None] = '9621ab45ec8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('visitor_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('interest_level', sa.Integer(), nullable=True),
    sa.Column('price_feedback', sa.String(), nullable=True),
    sa.Column('location_feedback', sa.String(), nullable=True),
    sa.Column('condition_feedback', sa.String(), nullable=True),
    sa.Column('lighting_feedback', sa.String(), nullable=True),
    sa.Column('elevator_feedback', sa.String(), nullable=True),
    sa.Column('garage_feedback', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_visits_id'), 'property_visits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_visits_id'), table_name='property_visits')
    op.drop_table('property_visits')
    # ### end Alembic commands ###
