"""add email phone status to clients

Revision ID: 75fe1a61b01f
Revises: 
Create Date: 2026-05-13 00:59:36.467924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75fe1a61b01f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('clients', 'status')
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###
