"""automatic reports config

Revision ID: a76caa7e1f1a
Revises: 711ff9f390ef
Create Date: 2026-06-03 20:09:55.769613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76caa7e1f1a'
down_revision: Union[str, Sequence[str], None] = '711ff9f390ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('auto_send_report', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('report_frequency', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('report_day', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('report_hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'report_hour')
    op.drop_column('properties', 'report_day')
    op.drop_column('properties', 'report_frequency')
    op.drop_column('properties', 'auto_send_report')
    # ### end Alembic commands ###
