"""add fair price and market entry date

Revision ID: b9588e7614f7
Revises: bd85d0d7e134
Create Date: 2026-06-02 11:18:05.909233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9588e7614f7'
down_revision: Union[str, Sequence[str], None] = 'bd85d0d7e134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('fair_price', sa.Numeric(), nullable=True))
    op.add_column('properties', sa.Column('market_entry_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'market_entry_date')
    op.drop_column('properties', 'fair_price')
    # ### end Alembic commands ###
