"""update report log fk set null

Revision ID: c2c34d595013
Revises: 5573324973ba
Create Date: 2026-06-10 23:23:59.941369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c34d595013'
down_revision: Union[str, Sequence[str], None] = '5573324973ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('report_job_logs_report_id_fkey'), 'report_job_logs', type_='foreignkey')
    op.create_foreign_key(None, 'report_job_logs', 'reports', ['report_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report_job_logs', type_='foreignkey')
    op.create_foreign_key(op.f('report_job_logs_report_id_fkey'), 'report_job_logs', 'reports', ['report_id'], ['id'])
    # ### end Alembic commands ###
